### ISSUE TITLE
[CHORE] 프로젝트 기본 세팅 추가

### ISSUE THREAD

**Issue by cnxw4570123** [SWYP-Woory/woory-backend#1]
## 어떤 작업인가요?

> 작업에 대해 간략하게 설명해주세요.

프로젝트 기본 세팅 작업

### 작업 상세 내용

- [x] 깃 커밋 템플릿 추가
- [x] 필요 라이브러리 추가

**Comment by DeveloperSeon** [comment]
확인했습니다.
